<h2>Liste des contacts</h2>

<table class="table">
    <?php foreach ($this->contacts as $c) : ?>
    <tr>
        <td><?= $c->getPrenom() ?> <?= $c->getNom() ?></td>
        <td>
            <a href="<?= $this->url('contact/show', ['id' => $c->getId()]) ?>">Afficher</a>
            <a href="<?= $this->url('contact/show/update', ['id' => $c->getId()]) ?>">Modifier</a>
            <a href="<?= $this->url('contact/show/delete', ['id' => $c->getId()]) ?>">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<a href="<?= $this->url('contact/add') ?>">
    Ajouter un contact
</a>