<h2>Liste des contacts</h2>

<table class="table">
    <?php foreach ($this->contacts as $c) : ?>
    <tr>
        <td><?= $this->escapeHtml($c->getPrenom()) ?> <?= $this->escapeHtml($c->getNom()) ?></td>
        <td>
            <a href="<?= $this->url('contact/show', ['id' => $this->escapeHtml($c->getId())]) ?>">Afficher</a>
            <a href="<?= $this->url('contact/show/update', ['id' => $this->escapeHtml($c->getId())]) ?>">Modifier</a>
            <a href="<?= $this->url('contact/show/delete', ['id' => $this->escapeHtml($c->getId())]) ?>">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<a href="<?= $this->url('contact/add') ?>">
    Ajouter un contact
</a>