<?php $this->headTitle()->append('Accueil'); ?>
<?php $this->placeholder('navbar-title')->append('Accueil'); ?>

<?php $this->headStyle()->captureStart(); ?>
body {
  background: beige;
}
<?php $this->headStyle()->captureEnd(); ?>

<?php $this->placeholder('head-style')->captureStart(); ?>
<style>
    body {
        /* background: red; */
    }
</style>
<?php $this->placeholder('head-style')->captureEnd(); ?>



<?= $this->prenom ?>
<?= $prenom ?>
<?= $this->partial('application/index/_exemple', ['prenom' => 'Jean']) ?>